//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursyPKS
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUTOKARY_KIEROWCY
    {
        public int K_ID { get; set; }
        public int A_ID { get; set; }
        public string MARKA { get; set; }
        public string NR_REJ { get; set; }
        public string MODEL { get; set; }
        public string IMIE { get; set; }
        public string NAZWISKO { get; set; }
        public string PESEL { get; set; }
    }
}
