//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursyPKS
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUTOKARY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AUTOKARY()
        {
            this.KURSies = new HashSet<KURSY>();
        }
    
        public int A_ID { get; set; }
        public int K_ID { get; set; }
        public string NR_REJ { get; set; }
        public string MARKA { get; set; }
        public string MODEL { get; set; }
        public decimal LICZBA_MIEJSC { get; set; }
    
        public virtual KIEROWCY KIEROWCY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KURSY> KURSies { get; set; }
    }
}
