//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursyPKS
{
    using System;
    using System.Collections.Generic;
    
    public partial class MIEJSCOWOSC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MIEJSCOWOSC()
        {
            this.KURSies = new HashSet<KURSY>();
            this.KURSies1 = new HashSet<KURSY>();
            this.TRASAs = new HashSet<TRASA>();
        }
    
        public int M_ID { get; set; }
        public string NAZWA { get; set; }
        public string KOD_POCZTOWY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KURSY> KURSies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KURSY> KURSies1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRASA> TRASAs { get; set; }
    }
}
