//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursyPKS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PKSTEntities1 : DbContext
    {
        public PKSTEntities1()
            : base("name=PKSTEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AUTOKARY> AUTOKARies { get; set; }
        public virtual DbSet<KIEROWCY> KIEROWCies { get; set; }
        public virtual DbSet<KIERUNEK> KIERUNEKs { get; set; }
        public virtual DbSet<KURSY> KURSies { get; set; }
        public virtual DbSet<MIEJSCOWOSC> MIEJSCOWOSCs { get; set; }
        public virtual DbSet<TRASA> TRASAs { get; set; }
        public virtual DbSet<AUTOKARY_KIEROWCY> AUTOKARY_KIEROWCY { get; set; }
    
        public virtual ObjectResult<HARMONOGRAM_Result> HARMONOGRAM(Nullable<decimal> iD_KURSU)
        {
            var iD_KURSUParameter = iD_KURSU.HasValue ?
                new ObjectParameter("ID_KURSU", iD_KURSU) :
                new ObjectParameter("ID_KURSU", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HARMONOGRAM_Result>("HARMONOGRAM", iD_KURSUParameter);
        }
    
        public virtual ObjectResult<KIEROWCY_W_TRASIE_Result> KIEROWCY_W_TRASIE(Nullable<System.DateTime> dATA)
        {
            var dATAParameter = dATA.HasValue ?
                new ObjectParameter("DATA", dATA) :
                new ObjectParameter("DATA", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KIEROWCY_W_TRASIE_Result>("KIEROWCY_W_TRASIE", dATAParameter);
        }
    
        public virtual ObjectResult<POJAZDY_Result> POJAZDY()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<POJAZDY_Result>("POJAZDY");
        }
    
        public virtual ObjectResult<PRZEBIEG_TRASY_Result> PRZEBIEG_TRASY(Nullable<int> iD_KURSU)
        {
            var iD_KURSUParameter = iD_KURSU.HasValue ?
                new ObjectParameter("ID_KURSU", iD_KURSU) :
                new ObjectParameter("ID_KURSU", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PRZEBIEG_TRASY_Result>("PRZEBIEG_TRASY", iD_KURSUParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> RAPORT_P(Nullable<decimal> nR_KURSU)
        {
            var nR_KURSUParameter = nR_KURSU.HasValue ?
                new ObjectParameter("NR_KURSU", nR_KURSU) :
                new ObjectParameter("NR_KURSU", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("RAPORT_P", nR_KURSUParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> TYGODNIOWY_RAPORT_P(Nullable<System.DateTime> dATA1, Nullable<int> iD_KIERUNKU)
        {
            var dATA1Parameter = dATA1.HasValue ?
                new ObjectParameter("DATA1", dATA1) :
                new ObjectParameter("DATA1", typeof(System.DateTime));
    
            var iD_KIERUNKUParameter = iD_KIERUNKU.HasValue ?
                new ObjectParameter("ID_KIERUNKU", iD_KIERUNKU) :
                new ObjectParameter("ID_KIERUNKU", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("TYGODNIOWY_RAPORT_P", dATA1Parameter, iD_KIERUNKUParameter);
        }
    }
}
